GET http://localhost:5114/games

###
GET http://localhost:5114/games/1

###
GET http://localhost:5114/games/2

###
POST http://localhost:5114/games
Content-Type: application/json

{
    "name": "Final Fantasy XIV",
    "genreId": 2,
    "price": 9.99,
    "releaseDate": "2001-11-08"
}

###
PUT http://localhost:5114/games/2
Content-Type: application/json

{
    "name": "Mortal Combact",
    "GenreId": 3,
    "price": 8.99,
    "releaseDate": "2001-02-15"
}

###
DELETE http://localhost:5114/games/7
